
fridge1 = Fridge.create()

puts "Creating items..."

Item.create(item_name: "Milk", item_type: "Dairy", image: "Icons/milk.png", price: 4, quantity: 1, purchase_date: "01/15/2022", expiry_date: "02/10/2022", fridge_id: fridge1.id )
Item.create(item_name: "Chicken", item_type: "Meat", image: "Icons/fried-chicken.png", price: 6, quantity: 1, purchase_date: "01/12/2022", expiry_date: "10/19/2022", fridge_id: fridge1.id )
Item.create(item_name: "Cheese", item_type: "Dairy", image: "Icons/cheese.png", price: 3, quantity: 1, purchase_date: "02/12/2022", expiry_date: "03/5/2022", fridge_id: fridge1.id )
Item.create(item_name: "Eggs", price: 4, item_type: "Poultry", image: "Icons/eggs.png", quantity: 12, purchase_date: "02/12/2022", expiry_date: "03/5/2022", fridge_id: fridge1.id )
Item.create(item_name: "Strawberries", item_type: "Fruit", image: "Icons/strawberry.png", price: 4, quantity: 1, purchase_date: "02/12/2022", expiry_date: "03/5/2022", fridge_id: fridge1.id )
Item.create(item_name: "Blueberries", item_type: "Fruit", image: "Icons/blueberry.png", price: 4, quantity: 1, purchase_date: "02/12/2022", expiry_date: "03/5/2022", fridge_id: fridge1.id )
Item.create(item_name: "Blackberries", item_type: "Fruit", image: "Icons/blackberry.png", price: 4, quantity: 1, purchase_date: "02/12/2022", expiry_date: "03/5/2022", fridge_id: fridge1.id )
Item.create(item_name: "Tomatoes", item_type: "Fruit", image: "Icons/tomato.png", price: 4, quantity: 1, purchase_date: "02/12/2022", expiry_date: "03/5/2022", fridge_id: fridge1.id )
Item.create(item_name: "Steak", item_type: "Meat", image: "Icons/meat.png", price: 20, quantity: 1, purchase_date: "06/12/2021", expiry_date: "06/22/2021", fridge_id: fridge1.id )
Item.create(item_name: "Orange Juice", item_type: "Beverage", image: "Icons/juice.png", price: 4, quantity: 1, purchase_date: "06/12/2021", expiry_date: "06/22/2021", fridge_id: fridge1.id )
Item.create(item_name: "Beer", item_type: "Beverage", image: "Icons/beer-bottle.png", price: 9, quantity: 6, purchase_date: "06/12/2021", expiry_date: "06/22/2021", fridge_id: fridge1.id )
Item.create(item_name: "Salsa", item_type: "Dip", image: "Icons/dip.png", price: 5, quantity: 1, purchase_date: "02/12/2021", expiry_date: "04/22/2021", fridge_id: fridge1.id )
Item.create(item_name: "Hot Dogs", item_type: "Meat", image: "Icons/hot-dog.png", price: 3, quantity: 1, purchase_date: "04/12/2021", expiry_date: "07/22/2021", fridge_id: fridge1.id )
Item.create(item_name: "Ketchup", item_type: "Sauce", image: "Icons/ketchup.png", price: 4, quantity: 1, purchase_date: "02/12/2021", expiry_date: "04/22/2021", fridge_id: fridge1.id )
Item.create(item_name: "Mustard", item_type: "Sauce", image: "Icons/mustard.png", price: 5, quantity: 1, purchase_date: "02/12/2021", expiry_date: "04/22/2021", fridge_id: fridge1.id )
Item.create(item_name: "Hot Sauce", item_type: "Sauce", image: "Icons/chili-sauce.png", price: 5, quantity: 1, purchase_date: "02/12/2021", expiry_date: "04/22/2021", fridge_id: fridge1.id )
Item.create(item_name: "BBQ Sauce", item_type: "Sauce", image: "Icons/bbq.png", price: 5, quantity: 1, purchase_date: "02/12/2021", expiry_date: "04/22/2021", fridge_id: fridge1.id )
Item.create(item_name: "Lemonade", item_type: "Beverage", image: "Icons/lemonade.png", price: 5, quantity: 1, purchase_date: "02/12/2021", expiry_date: "04/22/2021", fridge_id: fridge1.id )
Item.create(item_name: "Sprite", item_type: "Beverage", image: "Icons/soda.png", price: 5, quantity: 1, purchase_date: "02/12/2021", expiry_date: "04/22/2021", fridge_id: fridge1.id )
Item.create(item_name: "Hummus", item_type: "Dip", image: "Icons/hummus.png", price: 5, quantity: 1, purchase_date: "02/12/2021", expiry_date: "04/22/2021", fridge_id: fridge1.id )
Item.create(item_name: "Guacamole", item_type: "Dip", image: "Icons/guacamole.png", price: 5, quantity: 1, purchase_date: "02/12/2021", expiry_date: "04/22/2021", fridge_id: fridge1.id )
Item.create(item_name: "Yogurt", item_type: "Dairy", image: "Icons/yogurt.png", price: 5, quantity: 1, purchase_date: "04/12/2021", expiry_date: "05/22/2021", fridge_id: fridge1.id )
Item.create(item_name: "Avocados", item_type: "Fruit", image: "Icons/avocado.png", price: 3, quantity: 3, purchase_date: "02/12/2021", expiry_date: "04/22/2021", fridge_id: fridge1.id )
Item.create(item_name: "Butter", item_type: "Dairy", image: "Icons/butter.png", price: 3, quantity: 1, purchase_date: "03/12/2021", expiry_date: "05/22/2021", fridge_id: fridge1.id )
Item.create(item_name: "Spinach", item_type: "Vegetable", image: "Icons/spinach.png", price: 3, quantity: 1, purchase_date: "02/12/2021", expiry_date: "04/22/2021", fridge_id: fridge1.id )
Item.create(item_name: "Bacon", item_type: "Meat", image: "Icons/bacon.png", price: 6, quantity: 1, purchase_date: "02/12/2021", expiry_date: "04/22/2021", fridge_id: fridge1.id )
Item.create(item_name: "Carrots", item_type: "Vegetable", image: "Icons/carrots.png", price: 3, quantity: 1, purchase_date: "02/12/2021", expiry_date: "04/22/2021", fridge_id: fridge1.id )
Item.create(item_name: "Celery", item_type: "Vegetable", image: "Icons/celery.png", price: 3, quantity: 1, purchase_date: "02/12/2021", expiry_date: "04/22/2021", fridge_id: fridge1.id )
Item.create(item_name: "Bell Pepper", item_type: "Vegetable", image: "Icons/bell-pepper.png", price: 3, quantity: 1, purchase_date: "02/12/2021", expiry_date: "04/22/2021", fridge_id: fridge1.id )
Item.create(item_name: "Ham", item_type: "Meat", image: "Icons/ham.png", price: 3, quantity: 1, purchase_date: "02/12/21", expiry_date: "04/22/2021", fridge_id: fridge1.id )
Item.create(item_name: "Mayonnaise", item_type: "Sauce", image: "Icons/mayonnaise.png", price: 3, quantity: 1, purchase_date: "02/12/2021", expiry_date: "04/22/2021", fridge_id: fridge1.id )
Item.create(item_name: "Pickles", item_type: "Vegetable", image: "Icons/pickle.png", price: 3, quantity: 1, purchase_date: "02/12/2021", expiry_date: "04/22/2021", fridge_id: fridge1.id )
puts "start th images"
Pic.create(name: "Lemonade", img: "Icons/lemonade.png" )
Pic.create(name: "Sprite", img: "Icons/soda.png" )
Pic.create(name: "Hummus",  img: "Icons/hummus.png" )
Pic.create(name: "Guacamole",  img: "Icons/guacamole.png" )
Pic.create(name: "Yogurt",  img: "Icons/yogurt.png")
Pic.create(name: "Avocados",img: "Icons/avocado.png" )
Pic.create(name: "Butter",  img: "Icons/butter.png" )
Pic.create(name: "Spinach",  img: "Icons/spinach.png" )
Pic.create(name: "Bacon",  img: "Icons/bacon.png")
Pic.create(name: "Carrots", img: "Icons/carrots.png" )


puts "✅ Done seeding!"
